### ISSUE TITLE
error installing dandisets 000026/000108/000249/000251

### ISSUE THREAD

**Issue by anhknguyen96** [dandi/dandisets#211] opened 2022-06-17 15:29 UTC
Hi,

I cloned the repo 2 weeks ago using `datalad install -r https://github.com/dandi/dandisets` (python 3.9), all of the dandisets were cloned except for 000026/000108/000249/000251, with the corresponding errors displayed.
I'm not sure what caused the errors and I'd appreciate some help. Thanks!

![Screenshot from 2022-06-05 14-09-15](https://user-images.githubusercontent.com/30437493/174329472-cea6abd6-77a0-4569-b358-23f900cb5273.png)
![Screenshot from 2022-06-05 14-10-04](https://user-images.githubusercontent.com/30437493/174329475-7e2508f6-39e0-4c87-bb40-f0a3def0d835.png)
![Screenshot from 2022-06-05 14-41-04](https://user-images.githubusercontent.com/30437493/174329476-ff9da351-762b-49c8-a48f-45c0a6b3724a.png)

.

**Comment by jwodder** [comment] 2022-06-17 16:30
I cannot reproduce this; cloning those modules works fine for me in a fresh Docker container.  Are you still having this problem?

I suspect that this may have just been an intermittent issue on GitHub's end.

**Comment by yarikoptic** [comment] 2022-06-21 11:42
confirming that `install` worked out, and I did get those dandisets:

```shell
$> ls -l {000026,000108,000249,000251}/dandiset.yaml 
-rw------- 1 yoh yoh 25722 Jun 21 06:28 000026/dandiset.yaml
-rw------- 1 yoh yoh  2078 Jun 21 06:27 000108/dandiset.yaml
-rw------- 1 yoh yoh  5237 Jun 21 06:28 000249/dandiset.yaml
-rw------- 1 yoh yoh  3638 Jun 21 06:28 000251/dandiset.yaml
```

I guess the original problems were due to some connection instabilities and/or github freaking out (not unheard of) under heavy load (after all you had done 175 clones).  As `datalad` doesn't retry on such fails, I have filed an issue there https://github.com/datalad/datalad/issues/6770 .  As there is nothing to fix in dandisets, I will close this issue.

**Closed as completed by yarikoptic** 2022-06-21 11:42 UTC

**Comment by anhknguyen96** [comment] 2022-06-21 17:10
Hi yes, sorry for the tardy response. I `datalad clone` individually these dandisets and it worked, so I guess it was connection issue on my part.
Thanks.
